language: go

go:
  - "1.18"

branches:
  only:
    - master

before_install:
  - go get -t -v ./...

script:
  - go test -coverprofile=coverage.out -covermode=atomic -race ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
