package xalfred

// ... 预设图标
var (
	IconWorkflow  = NewIcon("icon.png")
	IconAccount   = NewIcon(GetSysIconPath("Accounts.icns"))
	IconBurn      = NewIcon(GetSysIconPath("BurningIcon.icns"))
	IconClock     = NewIcon(GetSysIconPath("Clock.icns"))
	IconColor     = NewIcon(GetSysIconPath("ProfileBackgroundColor.icns"))
	IconColour    = NewIcon(GetSysIconPath("ProfileBackgroundColor.icns"))
	IconEject     = NewIcon(GetSysIconPath("EjectMediaIcon.icns"))
	IconError     = NewIcon(GetSysIconPath("AlertStopIcon.icns"))
	IconFavorite  = NewIcon(GetSysIconPath("ToolbarFavoritesIcon.icns"))
	IconFavourite = NewIcon(GetSysIconPath("ToolbarFavoritesIcon.icns"))
	IconGroup     = NewIcon(GetSysIconPath("GroupIcon.icns"))
	IconHelp      = NewIcon(GetSysIconPath("HelpIcon.icns"))
	IconHome      = NewIcon(GetSysIconPath("HomeFolderIcon.icns"))
	IconInfo      = NewIcon(GetSysIconPath("ToolbarInfo.icns"))
	IconNetwork   = NewIcon(GetSysIconPath("GenericNetworkIcon.icns"))
	IconNote      = NewIcon(GetSysIconPath("AlertNoteIcon.icns"))
	IconSettings  = NewIcon(GetSysIconPath("ToolbarAdvanced.icns"))
	IconSwirl     = NewIcon(GetSysIconPath("ErasingIcon.icns"))
	IconSwitch    = NewIcon(GetSysIconPath("General.icns"))
	IconSync      = NewIcon(GetSysIconPath("Sync.icns"))
	IconTrash     = NewIcon(GetSysIconPath("TrashIcon.icns"))
	IconUser      = NewIcon(GetSysIconPath("UserIcon.icns"))
	IconWarning   = NewIcon(GetSysIconPath("AlertCautionIcon.icns"))
	IconWeb       = NewIcon(GetSysIconPath("BookmarkIcon.icns"))
)
