name: Go CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install
        run: go get -t -v ./...

      - name: Test
        run: go test -coverprofile=coverage.out -covermode=atomic -race ./...

      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash) -f coverage.out
